/**
 * Application Constants and Enums
 * Strictly enforces lifecycle stages, roles, statuses, and error categories
 */

const ROLES = {
  STUDENT: 'STUDENT',
  COUNSELOR: 'COUNSELOR',
  ADMIN: 'ADMIN',
};

const LIFECYCLE_STAGES = {
  REGISTERED: 'REGISTERED',
  LEAD: 'LEAD',
  APPLICATION_STARTED: 'APPLICATION_STARTED',
  APPLICATION_COMPLETED: 'APPLICATION_COMPLETED',
  DOCUMENTS_PENDING: 'DOCUMENTS_PENDING',
  DOCUMENT_VERIFICATION: 'DOCUMENT_VERIFICATION',
  ELIGIBILITY_CHECK: 'ELIGIBILITY_CHECK',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  ADMISSION_REVIEW: 'ADMISSION_REVIEW',
  ADMISSION_APPROVED: 'ADMISSION_APPROVED',
  ENROLLMENT_GENERATED: 'ENROLLMENT_GENERATED',
  ENROLLED: 'ENROLLED',
};

// Lifecycle transition sequence for state machine
const LIFECYCLE_ORDER = [
  LIFECYCLE_STAGES.REGISTERED,
  LIFECYCLE_STAGES.LEAD,
  LIFECYCLE_STAGES.APPLICATION_STARTED,
  LIFECYCLE_STAGES.APPLICATION_COMPLETED,
  LIFECYCLE_STAGES.DOCUMENTS_PENDING,
  LIFECYCLE_STAGES.DOCUMENT_VERIFICATION,
  LIFECYCLE_STAGES.ELIGIBILITY_CHECK,
  LIFECYCLE_STAGES.PAYMENT_PENDING,
  LIFECYCLE_STAGES.ADMISSION_REVIEW,
  LIFECYCLE_STAGES.ADMISSION_APPROVED,
  LIFECYCLE_STAGES.ENROLLMENT_GENERATED,
  LIFECYCLE_STAGES.ENROLLED,
];

const DOCUMENT_TYPES = {
  IDENTITY_PROOF: 'IDENTITY_PROOF',
  MARKSHEET_10TH: 'MARKSHEET_10TH',
  MARKSHEET_12TH: 'MARKSHEET_12TH',
  PASSPORT_PHOTO: 'PASSPORT_PHOTO',
  TRANSFER_CERTIFICATE: 'TRANSFER_CERTIFICATE',
  MIGRATION_CERTIFICATE: 'MIGRATION_CERTIFICATE',
  CATEGORY_CERTIFICATE: 'CATEGORY_CERTIFICATE',
  INCOME_CERTIFICATE: 'INCOME_CERTIFICATE',
};

const DOCUMENT_STATUS = {
  NOT_UPLOADED: 'NOT_UPLOADED',
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  MISMATCH: 'MISMATCH',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  SUPERSEDED: 'SUPERSEDED',
};

const DOCUMENT_VERSION_STATUS = {
  CURRENT: 'CURRENT',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
};

const ELIGIBILITY_STATUS = {
  ELIGIBLE: 'ELIGIBLE',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  PENDING: 'PENDING',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const ADMISSION_STATUS = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CONDITIONAL: 'CONDITIONAL',
  WITHDRAWN: 'WITHDRAWN',
};

const COUNSELOR_CASE_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

const COUNSELOR_CASE_CATEGORY = {
  FEE_WAIVER: 'FEE_WAIVER',
  POLICY_EXCEPTION: 'POLICY_EXCEPTION',
  DOCUMENT_AMBIGUITY: 'DOCUMENT_AMBIGUITY',
  LOW_AI_CONFIDENCE: 'LOW_AI_CONFIDENCE',
  PAYMENT_DISPUTE: 'PAYMENT_DISPUTE',
  SPECIAL_ACCOMMODATION: 'SPECIAL_ACCOMMODATION',
  COMPLAINT: 'COMPLAINT',
  HUMAN_REQUEST: 'HUMAN_REQUEST',
};

const COUNSELOR_CASE_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

const NOTIFICATION_TYPES = {
  EMAIL: 'EMAIL',
  IN_APP: 'IN_APP',
  WHATSAPP: 'WHATSAPP',
};

const NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  SENDING: 'SENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
};

const ERROR_CATEGORIES = {
  USER_ERROR: 'USER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  AWS_ERROR: 'AWS_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  AI_ERROR: 'AI_ERROR',
  DOCUMENT_ERROR: 'DOCUMENT_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
};

const COST_PROTECTION_LEVELS = {
  NORMAL: 'NORMAL',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
  EMERGENCY: 'EMERGENCY',
  HARD_PROTECTION: 'HARD_PROTECTION',
};

const COST_PROTECTION_EVENTS = {
  AWS_COST_NORMAL: 'AWS_COST_NORMAL',
  AWS_COST_WARNING: 'AWS_COST_WARNING',
  AWS_COST_CRITICAL: 'AWS_COST_CRITICAL',
  AWS_EMERGENCY_SHUTDOWN: 'AWS_EMERGENCY_SHUTDOWN',
  AWS_HARD_PROTECTION: 'AWS_HARD_PROTECTION',
  AWS_SERVICE_DISABLED: 'AWS_SERVICE_DISABLED',
  AWS_SERVICE_STOPPED: 'AWS_SERVICE_STOPPED',
  AWS_SERVICE_RESUMED: 'AWS_SERVICE_RESUMED',
  AWS_TEXTRACT_BLOCKED: 'AWS_TEXTRACT_BLOCKED',
  AWS_SES_BLOCKED: 'AWS_SES_BLOCKED',
  AWS_SQS_BLOCKED: 'AWS_SQS_BLOCKED',
  AWS_USAGE_LIMIT_EXCEEDED: 'AWS_USAGE_LIMIT_EXCEEDED',
  AWS_MONITORING_FAILURE: 'AWS_MONITORING_FAILURE',
  AWS_SIMULATION_UPDATED: 'AWS_SIMULATION_UPDATED',
};

module.exports = {
  ROLES,
  LIFECYCLE_STAGES,
  LIFECYCLE_ORDER,
  DOCUMENT_TYPES,
  DOCUMENT_STATUS,
  DOCUMENT_VERSION_STATUS,
  ELIGIBILITY_STATUS,
  PAYMENT_STATUS,
  ADMISSION_STATUS,
  COUNSELOR_CASE_PRIORITY,
  COUNSELOR_CASE_CATEGORY,
  COUNSELOR_CASE_STATUS,
  NOTIFICATION_TYPES,
  NOTIFICATION_STATUS,
  ERROR_CATEGORIES,
  COST_PROTECTION_LEVELS,
  COST_PROTECTION_EVENTS,
};

